import type { Metadata } from "next";
import "./globals.css";
import { Layout } from "@/types/Layout";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Blog- Learning NextJS",
  description: "Generated by create next app",
};

function RootLayout({ children }: Layout) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>{children}</body>
    </html>
  );
}

export default RootLayout;
